### ISSUE TITLE
not work

### ISSUE THREAD

**Issue by LyriD** [activeadmin-plugins/active_admin_datetimepicker#18]
rails 423, activeadmin 1.0.0.pre1

my admin/entity.rb

```

Entity.column_names.each do |column_name|
    filter column_name unless column_name == :updated_at
end

filter :updated_at, as: :date_time_range
```

initializers/active_admin.rb include:

```

ActiveAdminDatetimepicker::Base.default_datetime_picker_options = {
    defaultDate: proc { Time.current.strftime("%Y-%m-%d 00:00") }
}
# This if for backend(Ruby)
ActiveAdminDatetimepicker::Base.format = "%Y-%m-%d %H:%M"
```

and

`config.register_javascript 'active_admin_datetimepicker.js'
`

active_admin.css.scss contain:

```
@import "active_admin/mixins";
@import "active_admin/base";
@import "active_admin_datetimepicker";
```

i have empty fields in filters block. datetimepicker don't show. 
(web inspector is clean, no errors any)

Very very big thanks for reply!!

**Comment by workgena** [comment]
I reproduced your case. But it works fine. Perhaps you use old version. 

Try Gemfile:

``` ruby
gem 'active_admin_datetimepicker', '0.2.0'
```

**Comment by LyriD** [comment]
yes, i have 020 version. 
sorry, but still not working 4 me. all logs are pretty fine. 
magic О_о

**Comment by Fivell** [comment]
@LyriD , can you give sample application that reproduces bug

**Comment by Fivell** [comment]
@LyriD , try version 0.3.0, if doesn't help please reopen it with more information
