### ISSUE TITLE
multiple errors, unfortunately

### ISSUE THREAD

**Issue by okliv** [activeadmin-plugins/active_admin_datetimepicker#24]
```
Sass::SyntaxError - Undefined variable: "$filter-field-seperator-width".:
sass (3.4.22) lib/sass/script/tree/variable.rb:49:in `_perform'
sass (3.4.22) lib/sass/script/tree/node.rb:58:in `perform'
```

if i set this vars directly 

```
$filter-field-seperator-width: 20px;
$side-by-side-filter-input-width: 20px;
```

then new error appears

```
Formtastic::UnknownInputError - Unable to find input class for date_time_picker:
formtastic (3.1.4) lib/formtastic/helpers/input_helper.rb:379:in `rescue in input_class_by_trying'
```

rails 4.2.6
activeadmin 1.0.0.pre2

:(

**Comment by Fivell** [comment]
@okliv , please show your Gemfile and Gemfile.lock

**Comment by sutherland007** [comment]
I also have the same issue here it's my Gemfile and Gemfile.lock
[gemfiles.zip](https://github.com/activeadmin-plugins/active_admin_datetimepicker/files/330985/gemfiles.zip)
Hope it helps.

**Comment by Fivell** [comment]
@sutherland007 , @okliv ,

check that you included 
line 
`//= require active_admin_datetimepicker`
after 
`//= require active_admin/base`

And

`@import "active_admin_datetimepicker";`
after

```
@import "active_admin/mixins";
@import "active_admin/base";
```

**Comment by Fivell** [comment]
@sutherland007 , @okliv , feel free to reopen it with more details or link to test application with more details

**Comment by scarroll32** [comment]
I had the same issues ... and resolved via this post. Thanks.
