### ISSUE TITLE
Incorrect alignment on very wide pages

### ISSUE THREAD

**Issue by aselder** [activeadmin-plugins/active_admin_datetimepicker#27]
With very wide active admin pages, when using the `date_time_range` filter, the positioning of the date picker can be off.

See the attached picture. I have an even wide page where when you click on the filter, it looks like nothing happens because the date picker is off screen.

<img width="584" alt="screen shot 2016-12-14 at 7 51 39 am" src="https://cloud.githubusercontent.com/assets/11577/21189301/189a6f7e-c1d3-11e6-89b4-b0a0f1fc29ab.png">

**Comment by Fivell** [comment]
@aselder , test app with reproducing of this bug will be very helpful, thanks

**Comment by aselder** [comment]
@Fivell Sure thing.. May take a day or two, but I'll create a stripped down app for you.

**Comment by flentick** [comment]
@aselder, just add to a custom scss:

```
body.active_admin .xdsoft_datetimepicker {
  min-width: 320px;
}
```

**Comment by Fivell** [comment]
@workgena , what do you think ?

**Comment by workgena** [comment]
as jquery plugin **DateTimePicker** allows to use it just for Date or just for Time. Theoretically someone could setup this plugin with such options using config/initializers. In this case "min-width 320px" could be a problem.
