### ISSUE TITLE
Please release version 0.6 to rubygems

### ISSUE THREAD

**Issue by coderliu** [activeadmin-plugins/active_admin_datetimepicker#38]
As we can see on [https://rubygems.org/gems/active_admin_datetimepicker](https://rubygems.org/gems/active_admin_datetimepicker)

The latest version on rubygems is 0.5, which can not work under the guide. 

After change to 0.6 by

`gem 'active_admin_datetimepicker', git: 'https://github.com/activeadmin-plugins/active_admin_datetimepicker.git'`

It works.

Why don't you release version 0.6 to rubygems.org?
If there is anything I can do that can help the new version's releasing, I will try my best to help.

**Comment by coderliu** [comment]
I think #35 is a sample that 0.5 can not work follow the setup(config) guide which described in README.MD.

**Comment by workgena** [comment]
New [releases](https://rubygems.org/gems/active_admin_datetimepicker):
- 0.6.0 (ActiveAdmin 1.x compatibility)
- 0.6.1 (CSS-import fix)

**Comment by coderliu** [comment]
Thanks a lot
