### ISSUE TITLE
input_html isn't work

### ISSUE THREAD

**Issue by dengzhichao** [activeadmin-plugins/active_admin_datetimepicker#43]
this input_html not work
`f.input :expire_after, :as => :date_time_picker, :input_html => { :style => 'width: 100%', autocomplete: "off" }`

**Comment by ronnierios** [comment]
How did you set it up with the default behaviour? Greetings!

**Comment by workgena** [comment]
Provided example works fine on latest v1.1.0 version. 

"width: 100%" will look ugly and is not recommended for ActiveAdmin forms, unless you have custom styled form.

Please, make sure you follow steps in "Installation" section of README.
