### ISSUE TITLE
Deprecation warning for `register_stylesheet`

### ISSUE THREAD

**Issue by sunny** [activeadmin-plugins/active_admin_datetimepicker#48]
Using `activeadmin` v1.4.3, we get the following warning:

> DEPRECATION WARNING: Active Admin: The `register_stylesheet` config is deprecated and will be removed
> in v2. Import your "jquery.xdan.datetimepicker.css" stylesheet in the active_admin.scss.

**Comment by workgena** [comment]
Yes, I know this. But until 2.0 release, the `register_stylesheet ` is the only way to make CSS work in development and production mode.

Regular `@import jquery.xdan.datetimepicker` does not work properly in production mode.

Here are some details #44

PS: if you can help with other solution, it would be grate!

**Comment by sunny** [comment]
Thanks for the follow-up! I guess that the best thing to do for now is to wait for a solution from `active_admin`.
