### ISSUE TITLE
active_admin_datetimepicker submitted value attributes bug in commit e522459

### ISSUE THREAD

**Issue by Cusp2356** [activeadmin-plugins/active_admin_datetimepicker#54]
Commit e522459 - improve_input_html_options (#53), breaks datetimepicker functionality when an ActiveAdmin form is submitted. Hours and minutes are cut off the submitted value attributes, and the lteq value attribute is overwritten with the submitted gteq value attribute.

**Comment by workgena** [comment]
The bug is reproduce-able  even on earlier version. Working on a hotfix.

**Comment by workgena** [comment]
Version 0.7.2 released to the RubyGems. It should fix the issue.

Please notice that H:M works correctly only if column in database is `t.datetime` or `t.timestamp(s)`
