### ISSUE TITLE
inputs value converted to date on active_admin 2.0

### ISSUE THREAD

**Issue by senid231** [activeadmin-plugins/active_admin_datetimepicker#57]
after submit filters we see only date (without time) in inputs value

this patch fix the issue
```ruby
module DateTimeRangeInputPatch
  def input_html_options(input_name = gt_input_name, placeholder = gt_input_placeholder)
    super.tap do |options|
      options[:value] = current_value_for(input_name)
    end
  end

  def current_value_for(input_name)
    @object.public_send(input_name).to_s.to_time.strftime("%F %T")
  rescue
    ''
  end
end

ActiveAdmin::Inputs::Filters::DateTimeRangeInput.include DateTimeRangeInputPatch
```

**Comment by senid231** [comment]
gem version 0.7.1

**Comment by workgena** [comment]
Check the following:

1. The database column type is TIMESTAMP  or DATETIME
2. Html `id` attribute should end with `_datetime`

Here is some test cases `it 'submit filter form' do`:

https://github.com/activeadmin-plugins/active_admin_datetimepicker/blob/9b4051bc56caa9ef893a2bd66669c0a50c41ea2d/spec/filters_and_edit_form_spec.rb#L57-L61

**Comment by workgena** [comment]
And try 0.7.2 [diff](https://github.com/activeadmin-plugins/active_admin_datetimepicker/compare/v0.7.1...v0.7.2)

**Comment by Fivell** [comment]
@workgena it is  q_time_start_lteq

**Comment by Fivell** [comment]
time_start timestamp without time zone NOT NULL,

**Comment by workgena** [comment]
Does the error exist on 0.7.**2** ?

**Comment by senid231** [comment]
@workgena 0.7.2 works fine

thanks
