### ISSUE TITLE
How use "date_time_range" in a custom filter?

### ISSUE THREAD

**Issue by eugenio-caicedo** [activeadmin-plugins/active_admin_datetimepicker#66]
I need a custom param but It's not an attribute of my model. I need this param to filter the table with different columns. This is an example:

models/my_model.rb
````
class MyModel < ActiveRecord::Base
  #attributes: create_at, update_at
end
````

admin/my_model.rb
````
ActiveAdmin.register Team do
  filter :date, as: :date_time_range

  controller do
    def scoped_collection
       #filter here
    end
  end
end
````

But I get an error with that implementation.
````
undefined method `date_gteq_datetime_picker' for Ransack::Search<class: MyModel, base: Grouping <combinator: and>>:Ransack::Search
````
I guess the date column is not an attribute.

**Comment by workgena** [comment]
Yes, MyModel should have column in database named "date" with type as timestamp of date format.

**Comment by eugenio-caicedo** [comment]
Umm ok, thanks for the help.

**Comment by Fivell** [comment]
@eugenio-caicedo aa supports custom filters using ransackable scopes   try such approach https://stackoverflow.com/questions/48776246/custom-activeadmin-filter-for-date-range-complex-logic-in-method

**Comment by eugenio-caicedo** [comment]
@Fivell I'm not sure but I'll try to do it. Thanks for the suggestion.
