### ISSUE TITLE
Drop dependency "xdan-datetimepicker-rails"

### ISSUE THREAD

**Issue by workgena** [activeadmin-plugins/active_admin_datetimepicker#72]
### Background

Currently "active_admin_datetimepicker" has strong dependency on [shekibobo/xdan-datetimepicker-rails](https://github.com/shekibobo/xdan-datetimepicker-rails)

It provides Rails-wrapper for [xdan/datetimepicker](https://github.com/xdan/datetimepicker) JS-library.

**xdan-datetimepicker-rails** is abandoned and is not updates **since 2016**.

The last update for [xdan/datetimepicker](https://github.com/xdan/datetimepicker) JS-lib is dated **2020 year**.

### Proposition

Remove dependency on "shekibobo/xdan-datetimepicker-rails" and be dependant directly to "xdan/datetimepicker".

Or, create PR with update to xdan-datetimepicker-rails.

#### Related issues

* #68

**Comment by senid231** [comment]
i think we should just remove dependency, write instruction about how to install it via webpacker/sprockets and release major version (because it's a breaking change)
